[package]
name = "value-trait"
version = "0.2.10-alpha.0"
authors = ["Heinz N. Gies <heinz@licenser.net>"]
edition = "2018"
license = "Apache-2.0/MIT"
description = "Traits to deal with JSONesque values"
repository = "https://github.com/as-com/value-trait"
readme = "README.md"
documentation = "https://docs.rs/value-trait"
rust-version = "1.49"


[dependencies]
itoa = { version = "0.4", features = ["i128"] }
ryu = "1"
halfbrown = { git = "https://github.com/as-com/halfbrown.git", branch = "master" }
float-cmp = "0.9"

abi_stable = { version = "0.11.0", optional = true, default-features = false }

[features]
# Support for 128 bit integers
128bit = []

# Support for custom types
custom-types = []

preserve_order = ["halfbrown/indexmap", "halfbrown/ahash"]

# Support for abi-stable's `StableAbi` implementation
c-abi = ["abi_stable"]
