[package]
name = "value-trait"
version = "0.2.4-alpha.0"
authors = ["Heinz N. Gies <heinz@licenser.net>"]
edition = "2018"
license = "Apache-2.0/MIT"
description = "Traits to deal with JSONesque values"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itoa = { version = "0.4", features = ["i128"] }
ryu = "1"
halfbrown = { git = "https://github.com/as-com/halfbrown.git", branch = "master" }
float-cmp = "0.8"

[features]
# Support for 128 bit integers
128bit = []

# Support for custom types
custom-types = []

preserve_order = ["halfbrown/indexmap", "halfbrown/ahash"]
