name: Tests

on: [push]

jobs:
  build:
    strategy:
      matrix:
        rust:
          - stable
          - nightly
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        env:
          RUSTFLAGS: -D warnings
        rustflags:
          - "-C target-cpu=native"
          - "-C target-cpu=native -C target-feature=-avx2"
        features:
          - ""
          - "--features c-abi"
          - "--features 128bit"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Build
        env:
          RUSTFLAGS: ${{ matrix.rustflags }}
        run: cargo build ${{ matrix.features }}
      - name: Run tests
        env:
          RUSTFLAGS: ${{ matrix.rustflags }}
        run: cargo test ${{ matrix.features }}
